Updated signals
localcontexts/localcontextshub pull request #117
Opened 2024-02-28 19:40 UTC by sab-LC

2024-02-28 19:42 UTC, arojas1 commented
Task linked: [CU-8687fv9bk Fix Bugs on Develop](https://app.clickup.com/t/8687fv9bk)

2024-03-04 21:45 UTC, birbjam requested changes
Check and solve build issues.

2024-03-05 16:34 UTC, sab-LC commented
> Check and solve build issues.

@birbjam these are not build issues, The branch was previously pointing to the develop instance which is why it is showing as failed(only on deploy).

2024-03-05 17:54 UTC, arojas1 approved these changes

2024-03-05 17:55 UTC, birbjam approved these changes

2024-03-08 10:19 UTC, merged