#8687yzynn: Validate Researcher Access
localcontexts/localcontextshub pull request #138
Opened 2024-03-25 22:59 UTC by lc-hd

2024-03-25 22:59 UTC, arojas1 commented
Task linked: [CU-8687yzynn Change the way the system validates if user can view researcher pages](https://app.clickup.com/t/8687yzynn)

2024-03-26 18:20 UTC, birbjam requested changes
Please undo import deletions

2024-03-27 18:41 UTC, arojas1 approved these changes

2024-03-27 19:58 UTC, sab-LC approved these changes

2024-03-29 15:57 UTC, merged