#8688ahc1d font-awesome-change-host
localcontexts/localcontextshub pull request #174
Opened 2024-05-09 14:50 UTC by lc-hd

We are using a Font Awesome kit which loads Font Awesome 6.5.2. But sometimes that would fail.

This change uses a CDN for 6.5.2 to load Font Awesome.

Below is an image that shows icons still work.

![image](https://github.com/localcontexts/localcontextshub/assets/145378945/f6f147db-2725-4631-8370-843d90b37585)

2024-05-09 14:50 UTC, arojas1 commented
Task linked: [CU-8688ahc1d Explore Hosting Font Awesome Resources Ourselves](https://app.clickup.com/t/8688ahc1d)

2024-05-10 11:15 UTC, sab-LC approved these changes

2024-05-13 17:01 UTC, arojas1 approved these changes

2024-05-13 17:35 UTC, birbjam requested changes
Change URL to Pro Kit provided in Slack.

2024-05-16 16:06 UTC, lc-hd commented
Since the outage due to the Font Awesome Kit is rare, I'm closing this PR.

2024-05-16 16:06 UTC, closed without merging