#86880yzda Broken Admin Tables link in Admin Dashboard
localcontexts/localcontextshub pull request #189
Opened 2024-05-22 15:21 UTC by sab-LC

**[Issue:](https://app.clickup.com/t/86880yzda)**

**Description:**
The link to the admin table is broken and giving back 500 error.

**Solution:**
- Updated the link with correct URL.

**Before:**

https://github.com/localcontexts/localcontextshub/assets/145371882/ef79fd83-50a9-4f43-abb4-cf4baa1c6976

 
**After:**

https://github.com/localcontexts/localcontextshub/assets/145371882/9575e9ea-d819-4be0-af1c-1576f917a9bd

2024-05-22 15:21 UTC, arojas1 commented
Task linked: [CU-86880yzda Broken Admin Tables link in Admin Dashboard](https://app.clickup.com/t/86880yzda)

2024-05-22 16:37 UTC, birbjam commented
I know this is a work in progress but can you also address the error when Projects is clicked:

https://github.com/localcontexts/localcontextshub/assets/41635757/9f50773a-8e13-4c26-9e86-7dc1b95bf17a

2024-05-23 12:15 UTC, sab-LC commented
> I know this is a work in progress but can you also address in this PR the error when Projects is clicked:
> 
>  Screen.Recording.2024-05-22.at.9.36.54.AM.mov


https://github.com/localcontexts/localcontextshub/assets/145371882/1ef49392-8af1-4854-b686-9514dae1a292

2024-05-23 15:31 UTC, birbjam approved these changes
Looks good!

2024-05-23 15:59 UTC, lc-hd approved these changes

2024-05-23 16:08 UTC, arojas1 requested changes
It worked in the last video but it isn't working on my end. The Admin tables that should be linked to from dashboard should be the tables under the "Administration" section. On my end it is going to the admin home page but it should show this page instead: ![image](https://github.com/localcontexts/localcontextshub/assets/60452620/7babf1d5-fa55-4310-a833-18c9967d584c)

2024-05-28 17:29 UTC, arojas1 approved these changes

2024-05-28 19:08 UTC, merged