#86887gk2m Adjusted institution account functionality
localcontexts/localcontextshub pull request #202
Opened 2024-06-04 13:37 UTC by sab-LC

**[Issue:](https://app.clickup.com/t/86887gk2m)**

**Description:**
From the latest subscription meeting it was decided that some functionality was to be adjusted for accounts. This specific task relates to institutions only. 

- Public Projects can be viewed and downloaded regardless of subscription status
- Private Projects cannot be downloaded by anyone
- Institution accounts do appear in the registry but their public pages will contain content labelling them as Active (if subscription) and Inactive (if no subscription). Relevant task here: 
- Unsubscribed institutions cannot be added to Projects as contributors.
- Unsubscribed institutions cannot be joined via account creation process or from their public registry page.

**Solution:**
- Updated the Query for Projects on Project-board and for institutes on registry view
- Updated the Project model to get project access 
- Update the template to remove the Join button if Institute isn't subscribed

**After:**

https://github.com/localcontexts/localcontextshub/assets/145371882/a0da71e2-f3c5-4ece-a87a-2bf0ccc3588a

2024-06-04 13:37 UTC, arojas1 commented
Task linked: [CU-86887gk2m Institution account functionality adjustments](https://app.clickup.com/t/86887gk2m)

2024-06-06 18:44 UTC, lc-hd approved these changes

2024-06-07 20:30 UTC, birbjam requested changes
I realize that I worded this task in a possibly confusing manner when it comes to Private Projects.

They should not be appearing in the Projects Board, nor be viewable by anyone except members of a particular account which is was created in and the Project creator. Within that rule, they cannot be downloaded or shared by anyone who **can** access them.

2024-06-14 17:58 UTC, birbjam approved these changes

2024-06-14 18:10 UTC, merged