#86887gvrq user profile deactivation logic
localcontexts/localcontextshub pull request #205
Opened 2024-06-05 13:04 UTC by lc-hd

2024-06-05 13:04 UTC, arojas1 commented
Task linked: [CU-86887gvrq User profile deactivation: adjust logic](https://app.clickup.com/t/86887gvrq)

2024-06-07 20:38 UTC, birbjam requested changes
Two small changes:
- Support email a href, add class `default-a`
- For `When user is an account member` content update:

> It looks like you are a member of an account. Before you can deactivate your user profile, you need to leave each account. [LINK] Go to Accounts [LINK].

2024-06-10 21:51 UTC, birbjam commented
Feedback from the last hub standing:

- For the "user is an account member" flow, show the accounts the user is a part of between the text and the deactivation button, similar to what it looks like under Accounts.

Example of what the list would look like of the accounts the user is a part of. The list is between the content text and the button. Exclude the "You are the creator of this account" content and the Accounts content, that part is just an example of where to add the list itself.
![Screenshot 2024-06-10 at 2 38 15 PM](https://github.com/localcontexts/localcontextshub/assets/41635757/c3407ecb-ecd5-43fc-b156-e12a0b4e666d)

- Update content to say "It looks like you're a member of an account, when you deactive your profile, you will automatically be removed from any accounts you are a member of." 

@corrieroe can you look over the content for this?

2024-06-11 14:06 UTC, corrieroe commented
**When user is an account creator** - content looks fine

**When user is an account member**
It looks like you are a member of an account. When you deactivate your profile, you will be removed from all accounts and unable to log in. Your profile and its associated data will be deleted 30 days after deactivation.

**When user is neither an account creator, or an account member**
You will not be able to log in after you deactivate your profile. Your profile and its associated data will be deleted 30 days after deactivation.

2024-08-13 18:17 UTC, birbjam commented
@lc-hd is this a stale PR?

2024-08-15 14:42 UTC, lc-hd commented
@birbjam the PR has become stale but the features it introduces are still needed

2024-08-15 14:56 UTC, lc-hd commented
@birbjam The content changes have been implemented on this PR based on @corrieroe 's feedback and I created a [subtask](https://app.clickup.com/t/8689bxfry) for adding the accounts the user is a part of.

2024-08-15 15:34 UTC, lc-hd commented
when user is a creator

![image](https://github.com/user-attachments/assets/5834232c-2fbc-4390-b9ec-0c7272405aeb)

----

when is not a creator but is a member

![image](https://github.com/user-attachments/assets/a2a80f0e-b070-43c8-8c56-d230ff19eab5)




---

when user is neither a creator nor a member


![image](https://github.com/user-attachments/assets/48455034-d640-4c98-8bd5-577815b2bf28)

2024-08-15 21:37 UTC, lc-hd commented
After merging #294 into this branch, the content now shows the accounts the user is apart of. This is what it looks like now:


for creators:


https://github.com/user-attachments/assets/5565ae60-8f05-41f3-b0df-83f794996b4e



---

for members:

![image](https://github.com/user-attachments/assets/35a9c915-d10d-44fc-af93-09b2e5f7b824)

----

for non creator and non member

![image](https://github.com/user-attachments/assets/e1118489-724e-4cfb-b1a8-469f62345c70)

2024-08-16 16:40 UTC, arojas1 submitted a review, later dismissed
What about when the user is both an admin of an account and a member of others? This is what one of my admin accounts looks like atm and one of these accounts listed I am a member of, the others I am the creator. Maybe this list only shows for accounts that a user is a member of only and the list only shows if the user is not a main admin at all?
![image](https://github.com/user-attachments/assets/6001f1f1-67bb-4c73-8184-fa10254609be)

So it would be the following:
- Main Admin of at least 1 account: Text only
- Member of at least 1 account and NOT a main admin: Text and list
- Neither a member of an account nor a main admin: Text
--- 
The text for the user is a member only also makes it seem like I should be able to still click deactivate profile and it would automatically remove me from all accounts I am a member of, but the button does not allow any clicking. Do we want to add the functionality where when they click deactivate it removes them from all accounts or do we want to make users go to "Accounts" (manage-orgs) first to remove themselves from every account and then come back here to deactivate their profile?
![image](https://github.com/user-attachments/assets/f7e4aa6f-a021-4c0d-aa85-9ec9751c7c8e)

2024-08-19 20:16 UTC, lc-hd commented
> The text for the user is a member only also makes it seem like I should be able to still click deactivate profile and it would automatically remove me from all accounts I am a member of, but the button does not allow any clicking. Do we want to add the functionality where when they click deactivate it removes them from all accounts or do we want to make users go to "Accounts" (manage-orgs) first to remove themselves from every account and then come back here to deactivate their profile?

@arojas1 This is a good question. I'm thinking we can either:
a) keep the same functionality and change the wording on the button. 
Or 
b) keep the same wording on the button but change the functionality so one is able to click and deactivate those accounts.

2024-08-21 18:43 UTC, birbjam submitted a review, later dismissed
Based on our meeting with outreach, this PR should have the following functionality:

- When user is an account creator, they have to reach out to support to get their profile deactivated. (In this instance they can also be a member of other accounts, it does not matter because they have created at least one account).

- If a user is a member of an account OR a creator of an account AND has created a Project in any of the accounts they are a part of, they have to reach out to support for deactivation.

- If a user is a member of any accounts and they have not created any Projects, they can deactivate. Deactivation will remove them from any accounts they are a part of. 
(On the backend this means removing the user from the account instance [`community`, `institution`, `researcher`] admins, editors or viewers AND removing the target account from the user's `UserAffiliation` instance).
  - The accounts will be shown on the deactivation page and the content will remain the same as it currently is since removal from accounts will be happening automatically.

2024-08-28 18:50 UTC, lc-hd commented
Based on a discussion, this is the desired functionality on the deactivation page:
```
When is a creator or created a project
	list accounts that:
		-they created
		-they created projects with
	display hint for accounts they created:
		You're the creator of this account
	display hint for accounts they created:
		You've created projects for account					

When member
	list accounts they're members of 
	display hint: You will be remove from this accounts
	Deactivate button is active

When neither
	Deactivate button is active


**when deactivating:
	-remove user from account
	-remove user affiliation with account
```

2024-09-01 04:34 UTC, lc-hd commented
The has been updated based on feedback.

When the user is an account_creator or project_creator

https://github.com/user-attachments/assets/4fd1ea13-f30c-41ae-8f9e-0bea00ddf2b9

-------------------------------------------

When the user is only a member


https://github.com/user-attachments/assets/605ce8b4-616e-4c96-abda-a740254418b3

-----------------------------------------------

When the user is neither an (account_creator or project_creator), or a member of any account.


https://github.com/user-attachments/assets/dd947673-c7a8-42c9-808b-80c8ff97da51

2024-09-03 18:35 UTC, birbjam commented on accounts/views.py
> +            member_affiliations.delete()
Remove line 410 `member_affiliations.delete()`, we don't need to delete the `UserAffiliation` instance, just remove accounts from it. The deletion of this will occur when we are deleting the actual user from the hub. This is so that in case they made a mistake or wish to reactivate, there won't be an error thrown.

2024-09-03 18:40 UTC, birbjam commented on helpers/views.py
> +def determine_user_role(user: User) -> str:
Move `determine_user_role` function to `helpers/utils.py`.

2024-09-03 18:40 UTC, birbjam commented on helpers/views.py
> +def remove_user_from_account(user: User, account: Union[Community, Institution]) -> None:
Move `remove_user_from_account` function to `helpers/utils.py`.

2024-09-03 18:41 UTC, birbjam commented on helpers/views.py
> +def remove_user_from_affiliated_communities_and_institutions(user: User, affiliation: UserAffiliation) -> None:
Move `remove_user_from_affiliated_communities_and_institutions` function to `accounts/utils.py`.

2024-09-03 19:08 UTC, birbjam commented
Did a slight UI update with how the accounts are displayed.
<img width="1279" alt="Screenshot 2024-09-03 at 3 02 44 PM" src="https://github.com/user-attachments/assets/7bbe6d68-4673-4072-a608-0062e1874876">

2024-09-03 19:11 UTC, birbjam requested changes
Will approve once remaining comments are addressed, otherwise all looks and works great!

2024-09-06 16:25 UTC, birbjam submitted a review, later dismissed
Quick recap of our huddle:

- Create `remove_member_from_account` function in `accounts/utils.py` to include removing user from any institution or community account they are a part of and removing those accounts from the user's `UserAffiliation` instance but not deleting that instance. (This function is a combination of `remove_user_from_account` and `remove_user_from_affiliated_communities_and_institutions` functions into one).
- Use that new function in the `deactivate_user` view in `accounts/views.py` for when a user is a member of accounts only.

Once this PR is merged, use the same function in [this PR](https://github.com/localcontexts/localcontextshub/pull/301) `communities/views.py --> remove_member`, `institutions/views.py --> remove_member` and the `accounts/views.py --> manage_organizations` for when the user clicks the `Leave Account` button in the GUI. This will likely involve checking to see `if request.method == "POST"`.

2024-09-06 18:20 UTC, birbjam approved these changes

2024-09-06 18:21 UTC, merged