#8687c885q alert modification
localcontexts/localcontextshub pull request #237
Opened 2024-07-08 11:16 UTC by lc-hd

Toastr JS is being used to show the alerts instead of a div

2024-07-08 11:16 UTC, arojas1 commented
Task linked: [CU-8687c885q UI: Notifications / alerts to display differently](https://app.clickup.com/t/8687c885q)

2024-07-16 20:00 UTC, arojas1 requested changes
- Something ask in the next HSM, should the info bubble open up? if not, we either need to standardize shorter messages so they are completely visible on the bubble or have the bubble height adjust to fit longer messages.
- The opacity I think should be 1. The slight sheerness may make the message difficult to read at times.
- There needs to be some padding between the message and the line where the X is (see image)
![image](https://github.com/user-attachments/assets/785c78f1-0c23-44af-aa24-836bbc5d755c)

2024-07-19 19:38 UTC, lc-hd commented
@arojas1 thanks for the feedback, I updated the toast so the right padding is expanded and the opacity is always one.

Here's an image of what it looks like after the most recent change:
![image](https://github.com/user-attachments/assets/50376966-a5cb-4773-8d02-d3703e3bd180)


As far as the length of messages, currently the ellipsis is shown when the content is too long. Having that said, I'm think we may want to make the alert div longer than 325px so we can fit more content without the ellipsis.

2024-07-19 19:45 UTC, birbjam commented
The functionality of it looks good but I'm not a huge fan of the colors and opacity so I'm asking Renee to take a look at it before I approve this PR.

2024-07-29 21:16 UTC, lc-hd commented
I made updates based on Renee's feedback. Here's a preview of what that looks like.

![image](https://github.com/user-attachments/assets/1d3f2fc2-2609-44de-8656-ceb1d989d1b0)

2024-07-30 17:40 UTC, merged