#86891zwnh nld boundary links non json page
localcontexts/localcontextshub pull request #261
Opened 2024-07-24 01:38 UTC by lc-hd

Below are screenshots for various scenarios:

-------------

A Project with Boundary Derived from NLD

The url navigates to: https://native-land.ca/maps/territories/nansemond-2/
![image](https://github.com/user-attachments/assets/055ac2bf-424e-449a-9425-c44f0f8846ea)

-----

A Project with Boundary Derived from a Shapefile

![image](https://github.com/user-attachments/assets/299c9d42-cc82-4093-82e9-d2b0618de6b6)

---

A Project with Boundary and No Name

![image](https://github.com/user-attachments/assets/96a5790c-ed84-4e70-bc1c-d6d5cafb56d7)

2024-07-24 01:38 UTC, arojas1 commented
Task linked: [CU-86891zwnh NLD Boundary Link to non-JSON page](https://app.clickup.com/t/86891zwnh)

2024-07-24 19:31 UTC, birbjam requested changes
Looking good so far, requesting adjustments:

1. The name of the boundary should only appear in instances of NLD being used and only if the NLD URL is actually available for that boundary should it be hyperlinked. If there is a shapefile uploaded, do not include the file name at the top, but under the map it should say "This Project boundary originates from an uploaded shapefile" for now.

2. Capitalize Project for the text under the map.

3. The name of the hyperlinked boundary should be the size of regular text and should have less of a margin on the bottom (probably about 8px).

2024-07-25 16:53 UTC, arojas1 commented
> Looking good so far, requesting adjustments:
> 
>     1. The name of the boundary should only appear in instances of NLD being used and only if the NLD URL is actually available for that boundary should it be hyperlinked. If there is a shapefile uploaded, do not include the file name at the top, but under the map it should say "This Project boundary originates from an uploaded shapefile" for now.
The content for the text under the map if it is a shapefile should already be available from the community registry page example.

2024-07-30 14:19 UTC, lc-hd commented
This has been updated:

Boundary with NLD

![image](https://github.com/user-attachments/assets/f8128017-252e-4af7-9079-abeb9054558d)

----

Boundary with Shapefile

![image](https://github.com/user-attachments/assets/d11c332d-8259-4955-be9e-221739585c38)

2024-07-30 18:41 UTC, birbjam approved these changes
Looks good.

2024-07-30 18:46 UTC, merged