#8689c0ert 403 removing account bug fix
localcontexts/localcontextshub pull request #301
Opened 2024-08-22 17:06 UTC by lc-hd

This change allows users to remove themselves given they are not an admin

2024-08-22 17:06 UTC, arojas1 commented
Task linked: [CU-8689c0ert Removing Account Raises 403 Error](https://app.clickup.com/t/8689c0ert)

2024-08-22 17:15 UTC, birbjam requested changes
Only admins should be able to remove themselves from accounts on the account side. Users can only leave accounts from profile settings.

2024-08-22 17:31 UTC, lc-hd commented
@birbjam I have a question on this. I'll ask in Slack

2024-08-28 19:43 UTC, arojas1 commented
@lc-hd Based on our conversation, here are the use cases and next steps:
- Create a `remove_member` function to put into `helpers/utils.py`. Its only purpose is to remove a user from a community or institution.
    - Use existing code that is currently in the views below.
        - `community/views.py -> remove_member`
        - `institution/views.py - > remove_member`
        - `accounts/views.py -> manage_organizations`
- On Account Members page (per account):
    - Account creator and admins can remove members. They should have the option to remove members from that account. "Remove Member" should show and will call the Remove Member function from helpers
    - If a member viewing this page is NOT an admin, they should be able to have the option of leaving that account. "Leave Account" should show and will call the Remove Member function from helpers
- On Manage Orgs page (profile):
    - A user should be able to leave an account if they are not the creator of that account. "Leave Account" should show and will call the Remove Member function from helpers

2024-09-06 16:28 UTC, birbjam requested changes
Will wait for PR #205 to be adjusted and merged first, then updated to this PR as well before approval.

2024-09-10 20:05 UTC, birbjam commented
I am going to close this PR, will open a different one for this task.

2024-09-10 20:05 UTC, closed without merging