#8689ef9md-boundary-name-width
localcontexts/localcontextshub pull request #309
Opened 2024-08-28 16:16 UTC by lc-hd

This expands the boundary name width to take up the full width when necessary.

**On Project Boundary Page**
![image](https://github.com/user-attachments/assets/d1d6e71a-6991-4372-a0c7-c844a59fe18d)

----

**On Project Settings Page**
![image](https://github.com/user-attachments/assets/346c6c9d-2944-4882-bb30-46c87d011141)

2024-08-28 16:16 UTC, arojas1 commented
Task linked: [CU-8689ef9md Boundary Name in edit field cutting off name](https://app.clickup.com/t/8689ef9md)

2024-09-03 13:06 UTC, arojas1 requested changes
The max-width are not actually making the width of the input on my end taking up the full width of that space. I would recommend adding the `w-100` class to the input to take up the space.

Without `w-100`:
![image](https://github.com/user-attachments/assets/e44c573b-4d29-44d4-866b-ffbc299ecc75)

With `w-100`:
![image](https://github.com/user-attachments/assets/8cae2f2b-a9c9-4055-bd62-f5c4c8403cd6)
![image](https://github.com/user-attachments/assets/705a3bbd-bb52-4930-b01f-4fda7c61fa64)

2024-09-03 14:43 UTC, arojas1 approved these changes

2024-09-03 14:51 UTC, birbjam approved these changes

2024-09-03 15:04 UTC, merged