#86883chbv Bundle Request Process
localcontexts/localcontextshub pull request #330
Opened 2024-09-12 14:14 UTC by sab-LC

2024-09-12 14:14 UTC, arojas1 commented
Task linked: [CU-86883chbv Bundle Request Process](https://app.clickup.com/t/86883chbv)

2024-10-29 21:50 UTC, lc-hd approved these changes
LGTM

2024-10-31 17:39 UTC, arojas1 requested changes
Aside from two code comments, I think it would be best to update the settings page to have bundle and update subscription as two separate options. This is because they should have the option to inquire about a change in susbcription type or adding bundles, depending on what they would like (see figma example)
![Institution Subscription Settings - Admin view(1)](https://github.com/user-attachments/assets/3418c64c-51c2-4b54-bb72-c6054bfdd1ee)

Also, because they can purchase multiple bundles, I think having the option to select how many of each bundle type would make more sense, like in the figma below (though the pricing is missing in the figma so keeping that available makes sense)
![Institution Subscription Settings - Admin view](https://github.com/user-attachments/assets/ec025cf7-75ad-4f64-b60f-7d844068983b)

2024-10-31 17:39 UTC, arojas1 commented on accounts/models.py
> +    )
Service Provider can be removed from bundles since they will not have that option. They can also be removed from the subscription model as their process is now a bit different with the certification.

2024-10-31 17:39 UTC, arojas1 commented on accounts/models.py
> +    )
Communities can be removed from bundles since they will not have that option.

2024-10-31 22:03 UTC, birbjam commented on accounts/models.py
> +    )
+1

2024-10-31 22:03 UTC, birbjam commented on accounts/models.py
> +    )
+1

2024-10-31 22:04 UTC, birbjam commented
Looks good so far. I basically have the same comments as Ashley. Once those are addressed, I will approve.

2024-11-01 18:27 UTC, birbjam approved these changes

2024-11-01 21:14 UTC, merged