#8689k4q90 Notification mark all as read functionality
localcontexts/localcontextshub pull request #392
Opened 2024-10-29 20:45 UTC by sab-LC

**[Issue:](https://app.clickup.com/t/8689k4q90)**

**Description:**
Currently if you have multiple notifications in an account, you have to click through them one by one to mark them as Read. Would be great to have a Mark all as Read option in the Notifications box.
![image](https://github.com/user-attachments/assets/86e27fe0-daa0-48c5-ab03-57a197a10cad)

**Solution:**
- Added `mark_all_as_read` view in Notification app
- Added Mark all as read text on notification partials to call the view
- Adjusted Styling of templates according to figma
- Added CSS classes in css files

**After:**

2024-10-29 20:45 UTC, arojas1 commented
Task linked: [CU-8689k4q90 Mark All As Read functionality for account notifications](https://app.clickup.com/t/8689k4q90)

2024-10-31 17:56 UTC, arojas1 requested changes
When I went to mark notifications as read inside an account, the toast message showed twice (although I only clicked the button once) and the "Mark as Read" text was still clickable even though the notifications were already read.
![image](https://github.com/user-attachments/assets/b6b8df00-00cb-47cb-a13d-bb26f13f5203)

2024-11-14 22:25 UTC, birbjam approved these changes

2024-11-18 21:10 UTC, arojas1 approved these changes

2024-11-18 21:30 UTC, merged