8688rycc0 project person match project contributors
localcontexts/localcontextshub pull request #403
Opened 2024-11-12 22:18 UTC by lc-hd

2024-11-14 19:46 UTC, arojas1 commented
Task linked: [CU-8688rycc0 Make adding a Project Person match Project Contributors](https://app.clickup.com/t/8688rycc0)

2024-11-14 22:27 UTC, birbjam approved these changes

2024-11-18 21:39 UTC, arojas1 requested changes
When I tried adding a contributor, it did not show on the project page (video below)

https://github.com/user-attachments/assets/79b8dcc6-3b0e-4e97-9d39-f23e451b9b0f

2024-11-20 20:12 UTC, arojas1 approved these changes

2024-11-21 14:31 UTC, merged