#868ax1f21 Issue with Add translation form
localcontexts/localcontextshub pull request #409
Opened 2024-11-19 20:32 UTC by sab-LC

**[Issue:](https://app.clickup.com/t/868ax1f21)**

**Description:**
On the customize label page the Add translation button is behaving unexpectedly, adding a whole div instead of adding a translation form.
![image](https://github.com/user-attachments/assets/120c2d32-e1fa-4515-a819-6fe7c5f2abd6)

**Solution:**
- Updated `main.js` for rendering correct add-translation-form`

**Before:**

https://github.com/user-attachments/assets/1a8acea7-2fb6-4be1-b541-f5d15e1149f5

**After:**

2024-11-19 20:32 UTC, arojas1 commented
Task linked: [CU-868ax1f21 Issue with Add translation form in customize label](https://app.clickup.com/t/868ax1f21)

2024-11-25 22:21 UTC, birbjam approved these changes

2024-12-02 16:21 UTC, arojas1 requested changes
Looks good on the initial customize label page but when going to the edit label page, the add translation button and the prefill text for English, Maori, French and Spanish is not working.

So this functionality has to be added for `/edit/`, at the moment it is only added for `/customize/`. Video below of the edit process:

https://github.com/user-attachments/assets/a0b012be-1182-47e7-888a-8749d7b174b8

2024-12-06 20:28 UTC, birbjam approved these changes
Reviewed and testes with new commits which had addressed feedback and looks good to me.

2024-12-12 16:44 UTC, merged