#868b6n022 Disable Add a Member button
localcontexts/localcontextshub pull request #428
Opened 2024-12-09 19:58 UTC by sab-LC

2024-12-09 19:58 UTC, arojas1 commented
Task linked: [CU-868b6n022 Disable Add a Member button for unsubscribed institutions](https://app.clickup.com/t/868b6n022)

2024-12-11 17:20 UTC, arojas1 requested changes
The button should also have the same hover over as the `Create a Project` button when an account is not subscribed/a member
![image](https://github.com/user-attachments/assets/ea050057-a1ef-4446-aa1f-c9b766f92a80)

2024-12-13 00:19 UTC, birbjam commented
I haven't tested this locally yet, just looking at the code though it seems like its only checking `is_subscribed`, but I'm thinking of a use-case when an account has been subscribed at least once before but doesn't have an active subscription (ex. they were subscribed but the date of their subscription expired). They should still be able to add however many Viewers they want to the account.

For accounts that haven't subscribed yet at all, the button can be disabled.

2024-12-16 17:46 UTC, sab-LC commented
> I haven't tested this locally yet, just looking at the code though it seems like its only checking `is_subscribed`, but I'm thinking of a use-case when an account has been subscribed at least once before but doesn't have an active subscription (ex. they were subscribed but the date of their subscription expired). They should still be able to add however many Viewers they want to the account.
> 
> For accounts that haven't subscribed yet at all, the button can be disabled.

I updated the conditions, it will work now.

2024-12-18 18:14 UTC, arojas1 commented
> > I haven't tested this locally yet, just looking at the code though it seems like its only checking `is_subscribed`, but I'm thinking of a use-case when an account has been subscribed at least once before but doesn't have an active subscription (ex. they were subscribed but the date of their subscription expired). They should still be able to add however many Viewers they want to the account.
> > For accounts that haven't subscribed yet at all, the button can be disabled.
> 
> I updated the conditions, it will work now.

I just tested this and it looks like it is still blocking the buttons for when they have expired subscriptions. Take a look at the code from the subscription tab when it shows the "This subscription for this account has expired. Please renew your subscription." that is the same use case that would be for this instance as well. If the account has `is_subscribed` as False but there is an instance of the account in Subscription, they they would still have access to the Member buttons but only to be able to add Viewers. If `is_subscribed` is False and they don't have a Subscription instance then they never subscribed and shouldn't have access to the buttons.

2025-01-03 21:42 UTC, birbjam approved these changes
Nice, looks good! I had an account with an active subscription but no user count and I was able to add viewers.

2025-01-06 15:56 UTC, arojas1 requested changes
The button is still being blocked for me for an institution that is no longer subscribed but has an expired subscription but should be able to add viewers.
![image](https://github.com/user-attachments/assets/58335285-1892-40de-8417-ddc89b11feed)
![image](https://github.com/user-attachments/assets/d21da4c6-2fe1-478d-a988-fbdf37af9dc6)

2025-01-06 19:33 UTC, sab-LC commented
> The button is still being blocked for me for an institution that is no longer subscribed but has an expired subscription but should be able to add viewers. ![image](https://private-user-images.githubusercontent.com/60452620/400475816-58335285-1892-40de-8417-ddc89b11feed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxOTE5NTUsIm5iZiI6MTczNjE5MTY1NSwicGF0aCI6Ii82MDQ1MjYyMC80MDA0NzU4MTYtNTgzMzUyODUtMTg5Mi00MGRlLTg0MTctZGRjODliMTFmZWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDE5MjczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZWQwNGYyZjkzMzRhZTA2Mzc4ZmQ2MzI0MTczZTQ1YTAzNTg2NTE3ZmVmZTViY2I3ZmNlOTcxMjQ2MDgzNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YigTNq2AdX4__glxxhUIo1yN1TGSTLQLsaaeZNtY4X0) ![image](https://private-user-images.githubusercontent.com/60452620/400475951-d21da4c6-2fe1-478d-a988-fbdf37af9dc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxOTE5NTUsIm5iZiI6MTczNjE5MTY1NSwicGF0aCI6Ii82MDQ1MjYyMC80MDA0NzU5NTEtZDIxZGE0YzYtMmZlMS00NzhkLWE5ODgtZmJkZjM3YWY5ZGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDE5MjczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4YjNmYjViNjRiMTJkZmFlZDA5NDMzYzllY2VhNDIxM2YwYWEwMDQzMjhjODMzMThkMjgyNDI1ZjlkMGFkMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HehoiFf1zrhhRMeD83-S0xHj-1qCX2U5Ca_CCJJo1Pk)

This may be a potential bug: the subscription-settings page indicates that the subscription has expired, but the subscription record for this institute still exists in the database with an expired end_date.

2025-01-07 19:30 UTC, arojas1 commented
> > The button is still being blocked for me for an institution that is no longer subscribed but has an expired subscription but should be able to add viewers.
> 
> This may be a potential bug: the subscription-settings page indicates that the subscription has expired, but the subscription record for this institute still exists in the database with an expired end_date.

Is it possible to have the button hoverover show in a similar way to how the "expired" text shows in the subscription settings template?

Also, can you double check your merges are pulling from develop? because there were some content updates for the hoverover text that was merged from my last PR. Just to make sure the text doesn't need to be updated again.

2025-01-08 16:06 UTC, sab-LC commented
> > > The button is still being blocked for me for an institution that is no longer subscribed but has an expired subscription but should be able to add viewers.
> > 
> > 
> > This may be a potential bug: the subscription-settings page indicates that the subscription has expired, but the subscription record for this institute still exists in the database with an expired end_date.
> 
> Is it possible to have the button hoverover show in a similar way to how the "expired" text shows in the subscription settings template?
> 
> Also, can you double check your merges are pulling from develop? because there were some content updates for the hoverover text that was merged from my last PR. Just to make sure the text doesn't need to be updated again.

Displaying information like the subscription settings page may lead to increased bugs, as this is the standard comparison across other modules of the app. Additionally, having the `is_subscribed` attribute set to false while still having a subscription object in the database is not possible through the normal application flow; this can only be achieved via the admin panel. 
Yes, your content update is included in this file, as I have rebased it.

2025-01-08 16:33 UTC, arojas1 approved these changes
Approve for now but we may need to circle back to this at a later date

2025-01-08 17:00 UTC, merged