Added pointer-event none to labels/notices img's
localcontexts/localcontextshub pull request #48
Opened 2023-12-11 20:09 UTC by sab-LC

**[Issue:](https://app.clickup.com/t/8685v3xkd)**
  
- Description: Prevent others from downloading the icons from project pages instead of getting them from the api or project download.

**Solution:**
- Added pointer event none (css proporty) to labels/notices images.

**Before:**

https://github.com/localcontexts/localcontextshub/assets/145371882/70b133f8-ea1f-439b-8e06-cf98b47a9732

**After:**

https://github.com/localcontexts/localcontextshub/assets/145371882/3edf0cb7-0f2d-42ca-a657-df305b673cde

2023-12-11 23:16 UTC, birbjam approved these changes

2023-12-12 17:12 UTC, arojas1 requested changes
The Notices look good (still able to open the details to read about the Notices), but the Labels are no longer able to be clicked on to customize. It looks like the Notices are placed in a div that opens onClick but the Labels only triggered when the image was clicked and now the pointer events prevents that.

2023-12-12 23:13 UTC, birbjam commented
Having the same issue as Ashley, can't click on a Label to customize it.

2023-12-14 17:00 UTC, arojas1 approved these changes

2023-12-21 22:02 UTC, birbjam approved these changes

2023-12-22 16:47 UTC, merged

2024-02-08 17:28 UTC, arojas1 commented
Task linked: [CU-8685v3xkd Add pointer-events: none; to Label/Notice images on the hub](https://app.clickup.com/t/8685v3xkd)