Select Boundaries Via Shapefile
localcontexts/localcontextshub pull request #58
Opened 2024-01-08 10:16 UTC by lc-hd

This allows users to select boundaries by uploading a shapefile while creating an account.

------

# Happy Path Demo (typical use-case)

# Bad File Demo

https://github.com/localcontexts/localcontextshub/assets/145378945/ba90107f-f4be-43da-aebb-ca052ffe629e

-----

# Navigating to Other Pages Demo

https://github.com/localcontexts/localcontextshub/assets/145378945/e476a1fe-0073-4b8a-a4cc-80e425ee941e

2024-01-08 17:06 UTC, arojas1 requested changes
- Add a loading bar or wheel to show that the Zip file is being loaded (it can take a while sometimes depending on the file and this should prevent someone trying to add it multiple times)
- I tried uploading a ZIP with a shapefile of NYC and it kept saying the file wasn't accepted. Not sure if it is because there were too many zones or what but there may need to be some instructions on what is allow/accepted besides just file type. Or specifying why the file wasn't accepted if it is a ZIP file.

2024-01-24 01:41 UTC, lc-hd commented
* The UI on the other pages have remained the same but the admin page is different.
* The code has been refactored so only the first boundary will be used.
* When there is more than one boundary, the user will see a warning that only the first boundary will be used.

**New Admin page UI (for Communities)**

![image](https://github.com/localcontexts/localcontextshub/assets/145378945/310ac43f-1be6-4572-ab02-b4fb871b249e)

2024-01-24 19:02 UTC, birbjam approved these changes
LGTM

2024-01-24 19:18 UTC, sab-LC approved these changes

2024-01-24 20:13 UTC, merged