8686g6j1c notification indicator
localcontexts/localcontextshub pull request #60
Opened 2024-01-10 14:01 UTC by sab-LC

**[Issue:](https://app.clickup.com/t/8686g6j1c)**
  
- Description: There should be some indicator on the dasboard of any accounts that have notifications or how many notifications are in the account. Since the dashboard only shows notifications for the user's account, there is no way of knowing if an institution or community account the user is a part of has notifications pending unless the go into the account and look at the notification icon.

**Solution:**
- Added notification snippet to the dashboard's every card.
- Provided scope for notification snippet to get the notification of individual card.
- Handle notification for individual card and their read and unread status.

**Before:**
![notification(1)](https://github.com/localcontexts/localcontextshub/assets/145371882/b0e2bae6-6d13-4714-b591-b7e3d4a0aa63)

![notification(2)](https://github.com/localcontexts/localcontextshub/assets/145371882/3a1ed6c5-6577-4365-b8a0-58d77bb284f4)

**After:**

https://github.com/localcontexts/localcontextshub/assets/145371882/478d8682-2f32-46aa-9bd0-33258460deb3

2024-01-22 21:36 UTC, lc-hd approved these changes

2024-01-22 21:40 UTC, arojas1 approved these changes

2024-01-22 22:14 UTC, birbjam requested changes
I don't know if its just me, but when I click on the notification button for an account it opens but clicking on it again does not close the notification dropdown.

I thought maybe it was a caching issue so I did a hard reset in my browser but it did not make the issue go away.


https://github.com/localcontexts/localcontextshub/assets/41635757/13d499a1-a29f-47ec-a870-29f6332655f9

2024-01-23 13:53 UTC, sab-LC commented
> I don't know if its just me, but when I click on the notification button for an account it opens but clicking on it again does not close the notification dropdown.
> 
> I thought maybe it was a caching issue so I did a hard reset in my browser but it did not make the issue go away.
> 
>  Screen.Recording.2024-01-22.at.2.13.04.PM.mov

@birbjam resolved!

https://github.com/localcontexts/localcontextshub/assets/145371882/c9f4d072-95b7-4c4f-b0f9-8d12e5b930fc

2024-01-23 17:12 UTC, birbjam approved these changes

2024-01-24 19:26 UTC, merged

2024-02-08 17:32 UTC, arojas1 commented
Task linked: [CU-8686g6j1c Notification Indicator for account cards on dashboard](https://app.clickup.com/t/8686g6j1c)