#8686qked3 Added email verification using mail gun
localcontexts/localcontextshub pull request #98
Opened 2024-02-12 16:32 UTC by sab-LC

**[Issue:](https://app.clickup.com/t/8686qked3)**
  
- Description: Every few months we accumulate random users with suspicious emails that may or may not be legitimate, so we should set up an email checker on the backend using something like https://rapidapi.com/mr_admin/api/email-verifier to make sure only users with legitimate emails sign up.

**Solution:**
- Added a validation layer on top of registration to validate all the new user's emails. 
- Integrated mail-gun email validation for this purpose.

**Example**

<img width="810" alt="image" src="https://github.com/localcontexts/localcontextshub/assets/145371882/6e64c4b0-5aaa-4c64-9767-89924fc7096c">

- Before the mail-gun validation process, any email without the email format error(regex) was able to sign up into the hub. But now mail-gun will verify the email and check whether the mailbox for that email actually exist.

2024-02-12 18:59 UTC, arojas1 commented
Task linked: [CU-8686qked3 Hub registration: verify legitimate emails with something like Rapid API Verifier](https://app.clickup.com/t/8686qked3)

2024-02-14 10:30 UTC, lc-hd approved these changes

2024-02-15 18:30 UTC, lc-hd approved these changes

2024-02-16 15:51 UTC, arojas1 requested changes
When testing an email that isn't correct I got an error saying:
```
MissingSchema at /register/
Invalid URL 'None/address/validate': No scheme supplied. Perhaps you meant https://None/address/validate?
```
Will send an image of the error in Slack

2024-02-16 15:58 UTC, arojas1 approved these changes

2024-02-16 16:04 UTC, merged